
import{snapshot}from'./shared/growth.js';import{load,save,SCHOLAR_STATE_KEY}from'./shared/storage.js';import{go,render,route}from'./shared/router.js';import{ITEMS}from'./shared/collection.js';import{summary,cards}from'./subjects/latin.js';import{FRENCH_META}from'./subjects/french.js';
const V='0.1.0';let timer;
const set=(q,v)=>document.querySelectorAll(q).forEach(x=>x.textContent=String(v));
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>x.classList.remove('show'),2200)}
function growth(){const g=snapshot();set('[data-bind="level"]',g.level);set('[data-bind="xp-current"]',g.into);set('[data-bind="xp-next"]',g.next);set('[data-bind="medals"]',g.medals);set('[data-bind="collectibles"]',g.collectibles);set('[data-bind="study-days"]',g.studyDays);set('[data-bind="garden-stage"]',g.gardenStage);document.querySelectorAll('[data-bind="xp-bar"]').forEach(x=>x.style.width=`${Math.min(100,Math.round(g.into/g.next*100))}%`);set('[data-bind="xp-label"]',g.into/g.next>.7?'More growth is close.':'A new path begins.')}
function latin(){const s=summary();set('[data-bind="latin-count"]',s.questionCount.toLocaleString());set('[data-bind="latin-status"]',`${s.questionCount.toLocaleString()} source questions connected`);set('[data-bind="latin-progress"]',s.legacy?'Legacy progress detected':'New profile');document.getElementById('latinCategories').innerHTML=cards().map(c=>`<article><b>${String(c.n).padStart(2,'0')}</b><h3>${c.name}</h3><p>${c.copy}</p><small>${c.count.toLocaleString()} items classified</small></article>`).join('')}
function today(){const s=summary(),rows=[['Latin',`${s.questionCount.toLocaleString()} source-bank items`,'Ready'],['French',`${FRENCH_META.defaultSafeQuestions.toLocaleString()} audited default-safe questions`,'Adapter'],['Biology','No content loaded','Locked'],['Chemistry','No content loaded','Locked']];document.getElementById('todayPlan').innerHTML=rows.map(r=>`<div class="plan"><i></i><div><strong>${r[0]}</strong><small>${r[1]}</small></div><b>${r[2]}</b></div>`).join('')}
function collection(filter='all'){const state=load(),grid=document.getElementById('collectionGrid');grid.innerHTML=ITEMS.filter(x=>filter==='all'||x.category===filter).map(x=>`<article><div class="silhouette"></div><strong>${x.name}</strong><small>${state.collectibles[x.id]?'Earned through learning.':x.condition}</small></article>`).join('')}
function diag(){return{app:`Scholar's Garden Framework ${V}`,stateKey:SCHOLAR_STATE_KEY,growth:snapshot(),latin:summary(),french:FRENCH_META,biology:'locked',chemistry:'locked',imageStrategy:'lazy load + runtime cache'}}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r)return go(r.dataset.route);const l=e.target.closest('[data-locked]');if(l)return toast(`${l.dataset.locked} is intentionally locked.`);const f=e.target.closest('[data-filter]');if(f){document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===f));collection(f.dataset.filter)}})
window.addEventListener('hashchange',()=>render());document.addEventListener('lux:route',e=>{if(e.detail.route==='diagnostics')document.getElementById('diagnostics').textContent=JSON.stringify(diag(),null,2);growth()})
async function sw(){if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('./sw.js?v=0.1.0')}catch(e){console.warn('SW registration failed',e)}}
latin();today();collection();growth();render(route());sw();window.LuxFramework=Object.freeze({version:V,diagnostics:diag});
